name: 'Generate and publish Eiffel Events'
description: 'Generate and publish Eiffel Events using Eiffel REMReM Generate Service'
inputs:
  remrem_publish_service_url:
    description: 'URL to Eiffel REMReM Publish Service'
    required: true
    default: 'http://89.46.83.162:8080/generateAndPublish'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.remrem_publish_service_url }}
